export const LIGHT = {
  bg:"#f0f4f8", surface:"#ffffff", border:"#dde3ec",
  primary:"#003087", accent:"#e8000d", textMain:"#1a2233", textSub:"#5a6a82",
  ok:"#276749", okBg:"#f0fff4", alertBg:"#fff5f5", alertBorder:"#fc8181",
  header:"#ffffff", headerBorder:"#e8000d", inputBg:"#ffffff",
  modalBg:"#ffffff", tabBorder:"#dde3ec",
};

export const DARK = {
  bg:"#0f1117", surface:"#1a1d27", border:"#2d3148",
  primary:"#4d7cff", accent:"#ff4d4d", textMain:"#e8eaf0", textSub:"#8892a4",
  ok:"#48bb78", okBg:"#1a2e22", alertBg:"#2d1515", alertBorder:"#c53030",
  header:"#13151f", headerBorder:"#ff4d4d", inputBg:"#22263a",
  modalBg:"#1a1d27", tabBorder:"#2d3148",
};

export function makeStyles(C) {
  return {
    root:         { minHeight:"100vh", background:C.bg, fontFamily:"'Segoe UI','Helvetica Neue',Arial,sans-serif", color:C.textMain, transition:"background 0.2s,color 0.2s" },
    header:       { background:C.header, borderBottom:`4px solid ${C.headerBorder}`, minHeight:88, display:"flex", alignItems:"center", position:"relative", padding:"12px 0" },
    headerInner:  { flex:1, display:"flex", alignItems:"center", justifyContent:"center" },
    logo:         { height:60, maxWidth:260, objectFit:"contain" },
    darkBtn:      { position:"absolute", right:12, top:"50%", transform:"translateY(-50%)", background:"transparent", border:`1.5px solid ${C.border}`, borderRadius:8, padding:"5px 9px", cursor:"pointer", fontSize:18, color:C.textSub },
    pageWrap:     { maxWidth:1200, margin:"0 auto", padding:"20px 16px 48px" },
    titleStrip:   { display:"flex", alignItems:"flex-start", justifyContent:"space-between", marginBottom:20, gap:12, flexWrap:"wrap" },
    sysTitle:     { margin:0, fontSize:"clamp(18px,4vw,26px)", fontWeight:800, color:C.primary, letterSpacing:"-0.5px" },
    sysSub:       { margin:"2px 0 0", fontSize:13, color:C.textSub },
    rightActions: { display:"flex", alignItems:"center", gap:8, flexShrink:0 },
    alertBadge:   { background:C.accent, color:"#fff", border:"none", borderRadius:20, padding:"7px 14px", fontWeight:700, cursor:"pointer", fontSize:13, whiteSpace:"nowrap" },
    logoutBtn:    { background:"transparent", border:`1.5px solid ${C.border}`, color:C.textSub, borderRadius:8, padding:"7px 14px", cursor:"pointer", fontSize:13 },
    saveMsg:      { background:C.okBg, border:`1px solid ${C.ok}`, color:C.ok, borderRadius:8, padding:"10px 16px", marginBottom:16, fontWeight:600, fontSize:14 },
    saveMsgErr:   { background:C.alertBg, border:`1px solid ${C.accent}`, color:C.accent },
    saveMsgInfo:  { background:"#ebf4ff", border:`1px solid ${C.primary}`, color:C.primary },
    tabs:         { display:"flex", gap:2, borderBottom:`2px solid ${C.tabBorder}`, marginBottom:20, flexWrap:"wrap" },
    tab:          { background:"none", border:"none", padding:"10px 16px", cursor:"pointer", fontWeight:600, fontSize:"clamp(12px,3vw,14px)", color:C.textSub, borderBottom:"2px solid transparent", marginBottom:-2, transition:"all 0.15s", whiteSpace:"nowrap" },
    tabActive:    { color:C.primary, borderBottomColor:C.primary },
    loadingBar:   { display:"flex", alignItems:"center", gap:10, padding:"12px 0", marginBottom:10 },
    spinner:      { width:18, height:18, border:`3px solid ${C.border}`, borderTopColor:C.primary, borderRadius:"50%", display:"inline-block", animation:"spin 0.8s linear infinite" },
    loadingText:  { fontSize:13, color:C.textSub, fontStyle:"italic" },
    filterBar:    { display:"flex", gap:8, marginBottom:14, flexWrap:"wrap", alignItems:"center" },
    searchBox:    { flex:2, minWidth:140, padding:"9px 13px", border:`1.5px solid ${C.border}`, borderRadius:8, fontSize:14, outline:"none", background:C.inputBg, color:C.textMain },
    filterSelect: { flex:1, minWidth:120, padding:"9px 10px", border:`1.5px solid ${C.border}`, borderRadius:8, fontSize:13, outline:"none", background:C.inputBg, color:C.textMain, cursor:"pointer" },
    clearBtn:     { background:C.alertBg, color:C.accent, border:"none", borderRadius:8, padding:"9px 13px", cursor:"pointer", fontWeight:600, fontSize:13, whiteSpace:"nowrap" },
    reloadBtn:    { background:C.primary, color:"#fff", border:"none", borderRadius:8, padding:"9px 14px", cursor:"pointer", fontWeight:600, fontSize:13, whiteSpace:"nowrap" },
    desktopOnly:  { display:"block" },
    mobileOnly:   { display:"none" },
    tableWrap:    { overflowX:"auto", borderRadius:12, border:`1px solid ${C.border}`, background:C.surface, boxShadow:"0 2px 8px rgba(0,0,0,0.07)" },
    table:        { width:"100%", borderCollapse:"collapse", minWidth:600 },
    th:           { background:C.primary, color:"#fff", padding:"11px 13px", textAlign:"left", fontSize:11, fontWeight:700, letterSpacing:0.5, textTransform:"uppercase", whiteSpace:"nowrap" },
    tr:           { borderBottom:`1px solid ${C.border}` },
    trAlert:      { background:C.alertBg },
    td:           { padding:"10px 13px", fontSize:13, verticalAlign:"middle", color:C.textMain },
    emptyCell:    { padding:32, textAlign:"center", color:C.textSub },
    countNote:    { marginTop:8, fontSize:12, color:C.textSub },
    caBadge:      { background:C.okBg, color:C.primary, borderRadius:6, padding:"2px 8px", fontSize:11, fontWeight:600 },
    localBadge:   { borderRadius:6, padding:"3px 8px", fontSize:11, fontWeight:600 },
    localAlmox:   { background:C.okBg, color:C.ok },
    localST:      { background:C.okBg, color:C.primary },
    statusOk:     { background:C.okBg, color:C.ok, borderRadius:6, padding:"3px 8px", fontSize:11, fontWeight:700 },
    statusLow:    { background:C.alertBg, color:C.accent, borderRadius:6, padding:"3px 8px", fontSize:11, fontWeight:700 },
    actionRow:    { display:"flex", gap:6 },
    editBtn:      { background:C.okBg, color:C.primary, border:"none", borderRadius:6, padding:"5px 10px", cursor:"pointer", fontWeight:600, fontSize:12 },
    deleteBtn:    { background:C.alertBg, color:C.accent, border:"none", borderRadius:6, padding:"5px 10px", cursor:"pointer", fontWeight:600, fontSize:12 },
    qtyRow:       { display:"flex", alignItems:"center", gap:5 },
    qtyBtn:       { width:28, height:28, border:`1.5px solid ${C.border}`, borderRadius:6, background:C.inputBg, cursor:"pointer", fontWeight:700, fontSize:16, lineHeight:1, color:C.textMain },
    qtyInput:     { width:60, padding:"5px 6px", border:`1.5px solid ${C.border}`, borderRadius:6, fontSize:14, textAlign:"center", background:C.inputBg, color:C.textMain, outline:"none" },
    mobileCard:   { background:C.surface, border:`1.5px solid ${C.border}`, borderRadius:12, padding:"16px 14px", marginBottom:12, boxShadow:"0 1px 4px rgba(0,0,0,0.06)" },
    mobileCardHeader: { display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:8 },
    mobileCardName:   { fontWeight:700, fontSize:15, color:C.textMain, marginBottom:10 },
    mobileCardRow:    { display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:7 },
    mobileLabel:      { fontSize:12, color:C.textSub, fontWeight:600 },
    emptyMobile:      { textAlign:"center", color:C.textSub, padding:"24px 0" },
    uploadPanel:  { display:"flex", alignItems:"center", justifyContent:"space-between", gap:16, background:C.surface, border:`1.5px solid ${C.primary}`, borderRadius:12, padding:"16px 20px", marginBottom:14, flexWrap:"wrap" },
    uploadLeft:   { display:"flex", alignItems:"center", gap:14 },
    uploadIcon:   { fontSize:28 },
    uploadLabel:  { fontWeight:700, fontSize:14, color:C.textMain, marginBottom:3 },
    uploadHint:   { fontSize:12, color:C.textSub },
    uploadBtn:    { background:C.primary, color:"#fff", border:"none", borderRadius:8, padding:"10px 18px", cursor:"pointer", fontWeight:700, fontSize:13, whiteSpace:"nowrap", flexShrink:0, display:"inline-block" },
    previewBox:   { background:"#fffbeb", border:"1px solid #f6e05e", borderRadius:10, padding:"14px 16px", marginBottom:14 },
    previewHeader:{ display:"flex", alignItems:"center", justifyContent:"space-between", marginBottom:6, gap:10, flexWrap:"wrap" },
    previewCount: { fontSize:13, color:C.textSub },
    previewWarn:  { fontSize:13, color:"#744210", fontWeight:600 },
    invHeader:    { display:"flex", alignItems:"flex-start", justifyContent:"space-between", marginBottom:14, gap:12, flexWrap:"wrap" },
    invTitle:     { margin:"0 0 3px", fontSize:"clamp(16px,4vw,20px)", fontWeight:800, color:C.primary },
    invSubtitle:  { margin:0, fontSize:13, color:C.textSub },
    invActions:   { display:"flex", gap:8, alignItems:"center", flexShrink:0, flexWrap:"wrap" },
    invDirtyBanner: { background:"#fffbeb", border:"1px solid #f6e05e", color:"#744210", borderRadius:8, padding:"10px 14px", marginBottom:12, fontSize:13, fontWeight:600 },
    formCard:     { background:C.surface, borderRadius:12, border:`1px solid ${C.border}`, padding:"24px 20px", boxShadow:"0 2px 8px rgba(0,0,0,0.07)", maxWidth:680 },
    formTitle:    { margin:"0 0 20px", fontSize:18, fontWeight:800, color:C.primary },
    formGrid:     { display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))", gap:16 },
    field:        { display:"flex", flexDirection:"column", gap:4 },
    label:        { fontSize:11, fontWeight:700, color:C.textSub, textTransform:"uppercase", letterSpacing:0.5 },
    input:        { padding:"9px 12px", border:`1.5px solid ${C.border}`, borderRadius:8, fontSize:14, outline:"none", background:C.inputBg, color:C.textMain, width:"100%", boxSizing:"border-box" },
    fieldError:   { fontSize:12, color:C.accent },
    formActions:  { display:"flex", gap:10, marginTop:24, flexWrap:"wrap" },
    saveBtn:      { background:C.primary, color:"#fff", border:"none", borderRadius:8, padding:"11px 22px", cursor:"pointer", fontWeight:700, fontSize:14 },
    cancelBtn:    { background:C.border, color:C.textSub, border:"none", borderRadius:8, padding:"11px 16px", cursor:"pointer", fontWeight:600, fontSize:13 },
    alertTitle:   { fontSize:18, fontWeight:800, color:C.accent, marginBottom:8 },
    noAlerts:     { background:C.okBg, color:C.ok, borderRadius:12, padding:"28px 20px", textAlign:"center", fontWeight:600, fontSize:15, border:`1px solid ${C.ok}` },
    alertGrid:    { display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(260px,1fr))", gap:14 },
    alertCard:    { background:C.surface, border:`1.5px solid ${C.alertBorder}`, borderRadius:12, padding:18 },
    alertCardTop: { display:"flex", gap:12, alignItems:"flex-start", marginBottom:12 },
    alertNome:    { fontWeight:700, fontSize:14, marginBottom:2, color:C.textMain },
    alertCa:      { fontSize:12, color:C.textSub },
    alertStats:   { display:"grid", gridTemplateColumns:"1fr 1fr 1fr 1fr", gap:6 },
    alertStat:    { display:"flex", flexDirection:"column", alignItems:"center" },
    alertStatLabel: { fontSize:10, color:C.textSub, fontWeight:700, textTransform:"uppercase" },
    alertStatVal:   { fontSize:15, fontWeight:700, color:C.textMain },
    loginWrap:    { minHeight:"calc(100vh - 88px)", display:"flex", alignItems:"center", justifyContent:"center", padding:"16px" },
    loginCard:    { background:C.surface, borderRadius:16, border:`1px solid ${C.border}`, padding:"36px 28px", boxShadow:"0 8px 32px rgba(0,0,0,0.13)", width:"100%", maxWidth:380, textAlign:"center" },
    loginTitle:   { margin:"0 0 6px", fontSize:22, fontWeight:800, color:C.primary },
    loginSub:     { margin:"0 0 24px", fontSize:14, color:C.textSub },
    loginForm:    { display:"flex", flexDirection:"column", gap:12 },
    loginBtn:     { background:C.primary, color:"#fff", border:"none", borderRadius:8, padding:"13px", cursor:"pointer", fontWeight:700, fontSize:15, marginTop:4 },
    errorMsg:     { color:C.accent, fontSize:13, margin:0, fontWeight:600 },
    pwWrap:       { position:"relative", display:"flex", alignItems:"center" },
    pwInput:      { paddingRight:44 },
    pwToggle:     { position:"absolute", right:8, background:"transparent", border:"none", cursor:"pointer", fontSize:18, padding:"4px", color:C.textSub, lineHeight:1 },
    overlay:      { position:"fixed", inset:0, background:"rgba(0,0,0,0.5)", display:"flex", alignItems:"center", justifyContent:"center", zIndex:1000, padding:16 },
    modal:        { background:C.modalBg, borderRadius:14, padding:"28px 24px", width:"100%", maxWidth:400, boxShadow:"0 16px 48px rgba(0,0,0,0.28)", border:`1px solid ${C.border}` },
    modalTitle:   { margin:"0 0 10px", fontSize:17, fontWeight:800, color:C.accent },
    modalText:    { margin:"0 0 20px", fontSize:14, lineHeight:1.6, color:C.textMain },
    modalActions: { display:"flex", gap:10 },

    // ── Splash screen ──────────────────────────
    splashWrap:   { position:"fixed", inset:0, background:C.bg, display:"flex", flexDirection:"column", alignItems:"center", justifyContent:"center", zIndex:2000, gap:20 },
    splashLogo:   { height:90, maxWidth:320, objectFit:"contain", animation:"epi-pulse 1.6s ease-in-out infinite" },
    splashSpinner:{ width:34, height:34, border:`4px solid ${C.border}`, borderTopColor:C.primary, borderRadius:"50%", animation:"spin 0.8s linear infinite" },
    splashText:   { fontSize:13, color:C.textSub, fontWeight:600 },

    // ── Toast ──────────────────────────────────
    toastWrap:    { position:"fixed", bottom:20, left:"50%", transform:"translateX(-50%)", zIndex:3000, display:"flex", flexDirection:"column", gap:8, alignItems:"center", width:"calc(100% - 32px)", maxWidth:420 },
    toast:        { background:C.surface, border:`1.5px solid ${C.ok}`, color:C.ok, borderRadius:10, padding:"12px 20px", fontWeight:700, fontSize:14, boxShadow:"0 8px 24px rgba(0,0,0,0.18)", display:"flex", alignItems:"center", gap:10, animation:"epi-toast-in 0.25s ease-out", width:"100%", textAlign:"center", justifyContent:"center" },
    toastErr:     { borderColor:C.accent, color:C.accent },
    toastInfo:    { borderColor:C.primary, color:C.primary },

    // ── Tab content animation ─────────────────
    tabContent:   { animation:"epi-fade-in 0.25s ease-out" },

    // ── Dashboard ──────────────────────────────
    dashGrid:     { display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))", gap:14, marginBottom:20 },
    dashCard:     { background:C.surface, border:`1px solid ${C.border}`, borderRadius:14, padding:"20px 18px", boxShadow:"0 2px 8px rgba(0,0,0,0.06)", display:"flex", flexDirection:"column", gap:6, transition:"transform 0.15s" },
    dashCardIcon: { fontSize:26 },
    dashCardVal:  { fontSize:30, fontWeight:800, color:C.primary, lineHeight:1 },
    dashCardLabel:{ fontSize:12, color:C.textSub, fontWeight:600, textTransform:"uppercase", letterSpacing:0.4 },
    dashCardAlert:{ borderColor:C.alertBorder, background:C.alertBg },
    dashCardAlertVal: { color:C.accent },
    dashRow:      { display:"grid", gridTemplateColumns:"1fr 1fr", gap:16, marginBottom:20 },
    dashSection:  { background:C.surface, border:`1px solid ${C.border}`, borderRadius:14, padding:"18px 18px", boxShadow:"0 2px 8px rgba(0,0,0,0.06)" },
    dashSectionTitle: { fontSize:14, fontWeight:800, color:C.primary, marginBottom:14 },
    pieWrap:      { display:"flex", alignItems:"center", justifyContent:"center", gap:20, flexWrap:"wrap" },
    pieLegend:    { display:"flex", flexDirection:"column", gap:8 },
    pieLegendItem:{ display:"flex", alignItems:"center", gap:8, fontSize:13, color:C.textMain },
    pieDot:       { width:12, height:12, borderRadius:"50%", flexShrink:0 },
    criticoItem:  { display:"flex", justifyContent:"space-between", alignItems:"center", padding:"9px 0", borderBottom:`1px solid ${C.border}`, fontSize:13 },
    criticoNome:  { fontWeight:600, color:C.textMain },
    criticoCa:    { fontSize:11, color:C.textSub },
    criticoQtd:   { fontWeight:800, color:C.accent, fontSize:15 },

    // ── Histórico ───────────────────────────────
    histTimeline: { display:"flex", flexDirection:"column", gap:10 },
    histItem:     { background:C.surface, border:`1px solid ${C.border}`, borderRadius:10, padding:"12px 16px", display:"flex", alignItems:"flex-start", gap:12, animation:"epi-fade-in 0.25s ease-out" },
    histIconUp:   { fontSize:18, color:C.ok, flexShrink:0, marginTop:2 },
    histIconDown: { fontSize:18, color:C.accent, flexShrink:0, marginTop:2 },
    histBody:     { flex:1 },
    histTitle:    { fontSize:13, fontWeight:700, color:C.textMain },
    histMeta:     { fontSize:12, color:C.textSub, marginTop:2 },
    histDiff:     { fontWeight:800, fontSize:14, flexShrink:0, whiteSpace:"nowrap" },

    // ── Export buttons ──────────────────────────
    exportRow:    { display:"flex", gap:8, flexWrap:"wrap" },
    exportBtn:    { background:C.surface, color:C.primary, border:`1.5px solid ${C.primary}`, borderRadius:8, padding:"9px 16px", cursor:"pointer", fontWeight:700, fontSize:13, whiteSpace:"nowrap" },
  };
}
